import { Pool } from "pg";

    type GatewaySettings = { enabled: boolean; till: string };
    type SettingsRow = { admin_pin: string; till_number: string; paybill_number: string; gateway_enabled: boolean; commission_per_ten: string | number; withdraw_threshold: string | number; float_balance: string | number };
    type DashboardData = { balance: number; salesCount: number; revenue: number; totalCommissions: number; withdrawableCommissions: number; pendingCommissions: number; sales: Array<{ id: string; offerTitle: string; amount: number; paymentPhone: string; receivingPhone: string; commission: number; createdAt: string }>; customers: Array<{ phone: string; salesCount: number; totalSpend: number; lastSeen: string }> };

    let pool: Pool | undefined;
    let schemaPromise: Promise<void> | undefined;
    function getPool() { if (pool) return pool; const connectionString = process.env.POSTGRES_URL || process.env.DATABASE_URL; if (!connectionString) throw new Error("Missing POSTGRES_URL. Add a Vercel Postgres connection string to the production environment."); pool = new Pool({ connectionString, max: 1, idleTimeoutMillis: 10000, connectionTimeoutMillis: 10000, ssl: connectionString.includes("localhost") ? false : { rejectUnauthorized: false } }); return pool; }
    async function ensureSchema() { if (schemaPromise) return schemaPromise; schemaPromise = (async () => { const db = getPool(); await db.query("CREATE TABLE IF NOT EXISTS app_settings (id INTEGER PRIMARY KEY CHECK (id = 1), admin_pin TEXT NOT NULL DEFAULT '9898', till_number TEXT NOT NULL DEFAULT '3367738', paybill_number TEXT NOT NULL DEFAULT '4211224', gateway_enabled BOOLEAN NOT NULL DEFAULT FALSE, commission_per_ten NUMERIC NOT NULL DEFAULT 1.5, withdraw_threshold NUMERIC NOT NULL DEFAULT 10, float_balance NUMERIC NOT NULL DEFAULT 0, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE TABLE IF NOT EXISTS customers (id TEXT PRIMARY KEY DEFAULT md5(random()::text || clock_timestamp()::text), phone TEXT NOT NULL UNIQUE, purchases INTEGER NOT NULL DEFAULT 0, total_spent NUMERIC NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE TABLE IF NOT EXISTS sales (id TEXT PRIMARY KEY DEFAULT md5(random()::text || clock_timestamp()::text), offer_id TEXT NOT NULL, offer_title TEXT NOT NULL, service TEXT NOT NULL, price NUMERIC NOT NULL, commission NUMERIC NOT NULL DEFAULT 0, payment_phone TEXT NOT NULL, receiving_phone TEXT NOT NULL, for_self BOOLEAN NOT NULL DEFAULT TRUE, gateway_enabled BOOLEAN NOT NULL DEFAULT FALSE, destination TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', checkout_request_id TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE INDEX IF NOT EXISTS sales_created_at_idx ON sales (created_at DESC); CREATE TABLE IF NOT EXISTS withdrawals (id TEXT PRIMARY KEY DEFAULT md5(random()::text || clock_timestamp()::text), amount NUMERIC NOT NULL, phone TEXT, status TEXT NOT NULL DEFAULT 'requested', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());"); await db.query("INSERT INTO app_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING"); })().catch((error) => { schemaPromise = undefined; throw error; }); return schemaPromise; }
    async function query<T extends Record<string, unknown>>(text: string, values: unknown[] = []) { await ensureSchema(); return getPool().query<T>(text, values); }
    async function loadSettings(): Promise<SettingsRow> { const result = await query<SettingsRow>("SELECT * FROM app_settings WHERE id = 1"); const settings = result.rows[0]; if (!settings) throw new Error("Settings are not available right now."); return settings; }
    export async function getAdminPin() { try { return (await loadSettings()).admin_pin || "9898"; } catch { return "9898"; } }
    export async function getGatewaySettings(): Promise<GatewaySettings> { const s = await loadSettings(); return { enabled: s.gateway_enabled, till: /^\d{5,10}$/.test(s.till_number) ? s.till_number : "3367738" }; }
    export async function updateGatewaySettings(s: GatewaySettings) { await query("UPDATE app_settings SET gateway_enabled = $1, till_number = $2, updated_at = NOW() WHERE id = 1", [s.enabled, s.till]); return s; }
    export async function addFloat(amount: number) { const result = await query<{ float_balance: string }>("UPDATE app_settings SET float_balance = float_balance + $1, updated_at = NOW() WHERE id = 1 RETURNING float_balance", [amount]); if (!result.rows[0]) throw new Error("Could not add float."); return Number(result.rows[0].float_balance); }
    export async function recordConfirmedSale(input: { offerId: string; offerTitle: string; service: string; amount: number; paymentPhone: string; receivingPhone: string; paymentMode: "mpesa" | "float" }) { await ensureSchema(); const client = await getPool().connect(); try { await client.query("BEGIN"); const settings = (await client.query<SettingsRow>("SELECT * FROM app_settings WHERE id = 1 FOR UPDATE")).rows[0]; if (!settings) throw new Error("Settings are not available right now."); const commission = (input.amount / 10) * Number(settings.commission_per_ten); const destination = settings.gateway_enabled ? settings.till_number : settings.paybill_number; const sale = await client.query<{ id: string }>("INSERT INTO sales (offer_id, offer_title, service, price, commission, payment_phone, receiving_phone, for_self, gateway_enabled, destination, status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'paid') RETURNING id", [input.offerId, input.offerTitle, input.service, input.amount, commission, input.paymentPhone, input.receivingPhone, input.paymentPhone === input.receivingPhone, settings.gateway_enabled, destination]); await client.query("INSERT INTO customers (phone, purchases, total_spent, last_seen_at) VALUES ($1,1,$2,NOW()) ON CONFLICT (phone) DO UPDATE SET purchases = customers.purchases + 1, total_spent = customers.total_spent + EXCLUDED.total_spent, last_seen_at = NOW()", [input.receivingPhone, input.amount]); await client.query("COMMIT"); return { id: sale.rows[0]?.id ?? null, commission }; } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } }
    export async function getDashboardData(): Promise<DashboardData> { const settings = await loadSettings(); const [a,b,c] = await Promise.all([query<any>("SELECT * FROM sales ORDER BY created_at DESC LIMIT 100"), query<any>("SELECT * FROM customers ORDER BY last_seen_at DESC LIMIT 100"), query<any>("SELECT * FROM withdrawals ORDER BY created_at DESC LIMIT 200")]); const sales=a.rows; const customers=b.rows; const withdrawals=c.rows; const paid=sales.filter((x:any)=>x.status==='paid'); const earned=paid.reduce((n:number,x:any)=>n+Number(x.commission),0); const withdrawn=withdrawals.reduce((n:number,x:any)=>n+Number(x.amount),0); const available=Math.max(0,earned-withdrawn); const threshold=Number(settings.withdraw_threshold)||10; const withdrawable=Math.floor(available/threshold)*threshold; return { balance:Number(settings.float_balance), salesCount:paid.length, revenue:paid.reduce((n:number,x:any)=>n+Number(x.price),0), totalCommissions:Number(earned.toFixed(2)), withdrawableCommissions:Number(withdrawable.toFixed(2)), pendingCommissions:Number((available-withdrawable).toFixed(2)), sales:sales.map((x:any)=>({id:String(x.id),offerTitle:x.offer_title,amount:Number(x.price),paymentPhone:x.payment_phone,receivingPhone:x.receiving_phone,commission:Number(x.commission),createdAt:x.created_at})), customers:customers.map((x:any)=>({phone:x.phone,salesCount:x.purchases,totalSpend:Number(x.total_spent),lastSeen:x.last_seen_at})) }; }
    export async function requestCommissionWithdrawal(phone?: string | null) { const dashboard=await getDashboardData(); const amount=dashboard.withdrawableCommissions; if (!amount) return { amount: 0 }; await query("INSERT INTO withdrawals (amount, phone, status) VALUES ($1,$2,'requested')", [amount, phone ?? null]); return { amount }; }
    